theme: jekyll-theme-hacker

title:  Ewerton Massaaki
description: Something strange.
url: https://ewertonmassaaki.github.io

# Site Author
author:
  name: "Ewerton Massaaki"
  avatar: ""
  bio: "Embedded Systems Developer"
  location: Londrina/Brazil
  github: "ewertonmassaaki"
